# Generated by Django 6.0.5 on 2026-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadarFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('image_url', models.CharField(max_length=500)),
                ('layer', models.CharField(default='precipitation', max_length=50)),
            ],
            options={
                'db_table': 'radar_frames',
                'ordering': ['-timestamp'],
            },
        ),
    ]
