# Generated by Django 6.0.5 on 2026-05-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField(db_index=True)),
                ('temp_min', models.FloatField(help_text='Min temperature in Celsius')),
                ('temp_max', models.FloatField(help_text='Max temperature in Celsius')),
                ('temp_morn', models.FloatField(null=True)),
                ('temp_day', models.FloatField(null=True)),
                ('temp_eve', models.FloatField(null=True)),
                ('temp_night', models.FloatField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('pressure', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('wind_direction', models.IntegerField(null=True)),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=255)),
                ('weather_icon', models.CharField(max_length=10)),
                ('pop', models.FloatField(default=0.0, help_text='Probability of precipitation (0.0 to 1.0)')),
                ('rain', models.FloatField(default=0.0, help_text='Rain volume in mm')),
                ('snow', models.FloatField(default=0.0, help_text='Snow volume in mm')),
                ('uv_index', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'daily_forecasts',
                'ordering': ['date'],
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('pressure', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('wind_direction', models.IntegerField(null=True)),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=255)),
                ('weather_icon', models.CharField(max_length=10)),
                ('pop', models.FloatField(default=0.0, help_text='Probability of precipitation')),
                ('rain', models.FloatField(default=0.0)),
                ('snow', models.FloatField(default=0.0)),
                ('daily_forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='forecasts.dailyforecast')),
            ],
            options={
                'db_table': 'hourly_forecasts',
                'ordering': ['time'],
                'unique_together': {('latitude', 'longitude', 'time')},
            },
        ),
    ]
