# Generated by Django 6.0.5 on 2026-05-26 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(max_length=255)),
                ('metric', models.CharField(choices=[('temperature', 'Temperature (°C)'), ('humidity', 'Humidity (%)'), ('wind_speed', 'Wind Speed (m/s)'), ('aqi', 'Air Quality Index'), ('uv_index', 'UV Index'), ('rain', 'Rain probability')], max_length=20)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('equals', 'Equals')], max_length=10)),
                ('threshold', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('source', models.CharField(default='system', max_length=100)),
            ],
            options={
                'db_table': 'weather_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
