# Generated by Django 6.0.5 on 2026-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('soil_temperature', models.FloatField(help_text='Soil temperature in Celsius at 10cm depth')),
                ('soil_moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('evapotranspiration', models.FloatField(help_text='Daily rate in mm')),
                ('leaf_wetness', models.FloatField(help_text='Leaf wetness duration in hours')),
            ],
            options={
                'db_table': 'farming_metrics',
                'ordering': ['-created_at'],
            },
        ),
    ]
