# Generated by Django 6.0.5 on 2026-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(null=True)),
                ('temp_min', models.FloatField(null=True)),
                ('temp_max', models.FloatField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('pressure', models.FloatField(help_text='Pressure in hPa', null=True)),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s', null=True)),
                ('wind_direction', models.IntegerField(help_text='Wind direction in degrees', null=True)),
                ('wind_gust', models.FloatField(null=True)),
                ('visibility', models.IntegerField(help_text='Visibility in meters', null=True)),
                ('clouds', models.IntegerField(help_text='Cloudiness percentage', null=True)),
                ('weather_main', models.CharField(blank=True, max_length=50)),
                ('weather_description', models.CharField(blank=True, max_length=255)),
                ('weather_icon', models.CharField(blank=True, max_length=10)),
                ('sunrise', models.DateTimeField(null=True)),
                ('sunset', models.DateTimeField(null=True)),
                ('rain_1h', models.FloatField(help_text='Rain volume for last 1h in mm', null=True)),
                ('snow_1h', models.FloatField(help_text='Snow volume for last 1h in mm', null=True)),
                ('uv_index', models.FloatField(null=True)),
                ('dew_point', models.FloatField(null=True)),
                ('source', models.CharField(default='openweathermap', max_length=50)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='weather_dat_latitud_252755_idx'), models.Index(fields=['location_name', '-created_at'], name='weather_dat_locatio_32075b_idx')],
            },
        ),
    ]
