# Generated by Django 6.0.5 on 2026-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('aqi', models.IntegerField(help_text='Air Quality Index')),
                ('uv_index', models.FloatField()),
                ('pollen_tree', models.CharField(default='Low', max_length=20)),
                ('pollen_grass', models.CharField(default='Low', max_length=20)),
                ('pollen_ragweed', models.CharField(default='Low', max_length=20)),
                ('joint_pain_index', models.IntegerField(default=2, help_text='Joint pain risk scale 1-10')),
                ('asthma_risk', models.CharField(default='Low', max_length=20)),
                ('flu_risk', models.CharField(default='Low', max_length=20)),
            ],
            options={
                'db_table': 'health_metrics',
                'ordering': ['-created_at'],
            },
        ),
    ]
